### ISSUE TITLE
Transition from convert-hex to binstring

### ISSUE THREAD

**Issue by MidnightLightning** [cryptocoinjs/btc-script#3]
We decided to move away from `convert-hex` and `convert-string` being separate libraries and merge them into `binstring`. This module needs to move away from `convert-hex` to `binstring`.

**Comment by shesek** [comment]
This was done at https://github.com/cryptocoinjs/btc-script/commit/22deb471fbb39f3ca3122cbd8b80aee43ab8af1d.
